maplibre/ngx-maplibre-gl

.github/workflows/npm-publish.yml, projects/ngx-maplibre-gl/package.json
Please see https://github.com/maplibre/maplibre-gl-js/pull/231
@nyurik please share the organization secret `NPM_ORG_TOKEN` with this repository. Thank you!
=> Update CI for publishing under the NPM maplibre org

projects/showcase/cypress/e2e/language-switch.cy.ts, projects/showcase/cypress/support/e2e-driver.ts, tsconfig.json
Added e2e driver for complete decoupling between test (language-switch) and test framework (cypress), and for test readability.
=> decoupling test (language-switch) from testing framework (cypress)

package-lock.json, package.json
Update version of Cypress. This should (hopefully?) upgrade the CI environment to use 12.x instead of 10.x when it runs `npm ci`.
=> Update version of cypress

docs/API.md, projects/ngx-maplibre-gl/src/lib/control/navigation-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/terrain-control.directive.ts, projects/ngx-maplibre-gl/src/lib/map/map.component.ts, projects/ngx-maplibre-gl/src/lib/map/map.service.ts, projects/ngx-maplibre-gl/src/lib/ngx-maplibre-gl.module.ts, projects/ngx-maplibre-gl/src/public_api.ts, projects/showcase/cypress/e2e/terrain-control.cy.ts, projects/showcase/cypress/support/e2e-driver.ts, projects/showcase/src/app/demo/demo-index.component.ts, projects/showcase/src/app/demo/demo.module.ts, projects/showcase/src/app/demo/examples/ngx-terrain-control.component.ts, projects/showcase/src/app/demo/examples/terrain-map-style.component.ts, projects/showcase/src/app/demo/examples/terrain-map.component.ts, projects/showcase/src/app/demo/routes.ts
Expose the 3D Terrain functionality from maplibre-gl (first seen in version [v.2.2.0](https://github.com/maplibre/maplibre-gl-js/releases/tag/v2.2.0))
=> Expose MapLIbre-GL 3D Terrain functionality

docs/API.md, projects/ngx-maplibre-gl/src/lib/map/map.component.ts, projects/showcase/src/app/demo/examples/cluster-html.component.ts, projects/showcase/src/app/demo/examples/set-popup.component.ts
Replaced instances of "mapbox.com" urls with "maplibre.org" equivalents, if they could be found.
=> Change mapbox urls to maplibre's equivalent

projects/ngx-maplibre-gl/src/lib/control/control.component.ts, projects/showcase/cypress/e2e/ngx-custom-control.cy.ts, projects/showcase/cypress/support/e2e-driver.ts, projects/showcase/src/app/demo/examples/ngx-custom-control.component.ts
This fixes an issue with controls sometimes not being removed from the map when the control component is destroyed. For more details see https://github.com/maplibre/ngx-maplibre-gl/issues/85.
For the purpose of testing I also modified the custom control example and added a button that adds/removes the controls from the map. The tests now verify that the controls are removed.
=> Control removal fix

projects/ngx-maplibre-gl/src/lib/popup/popup.component.ts, projects/showcase/src/app/demo/examples/polygon-popup-on-click.component.ts
This modifies what happens when the value of the `lngLat` input of a popup component changes. 
The current behavior is to remove the old popup and then create a new popup at the new location. I would argue that this isn't optimal and that simply calling `setLngLat` on the existing popup would be a better solution.
My thought is that it probably originally was done this way to make sure that the popup always is open when the input changes, overriding the `closeOnClick` behavior. Regardless, this can be seen as a breaking change with perhaps only a small benefit. I can understand if you don't want to include it. 
The benefit of the change is mainly performance.  For example, making a popup work as a tooltip by following the mouse is more feasible after this change.
I modified the …
=> Popup moving change

.github/workflows/ci.yml, .github/workflows/npm-publish.yml, package-lock.json, package.json, projects/showcase/cypress/e2e/set-style.cy.ts
The node version needs to be 18 or above: https://github.com/lint-staged/lint-staged/releases/tag/v15.0.0
https://nodejs.dev/en/about/releases/
In `package.json` we forbid publishing to `npmjs.com` with `private: true`. Therefore the github workflow to publish is not necessary.
=> update lint-staged from 13 to 15

projects/showcase/src/app/demo/demo-index.component.html, projects/showcase/src/app/doc/doc.component.ts, projects/showcase/src/app/shared/layout/layout.component.ts
=> fix layout shift on mobile devices, move menu items to menu

.github/workflows/ci.yml, .github/workflows/gh-pages-push.yml, angular.json, package-lock.json, package.json, projects/ngx-maplibre-gl/src/lib/control/attribution-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/control.component.ts, projects/ngx-maplibre-gl/src/lib/control/fullscreen-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/geolocate-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/navigation-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/scale-control.directive.ts, projects/ngx-maplibre-gl/src/lib/control/terrain-control.directive.ts, projects/ngx-maplibre-gl/src/lib/draggable/draggable.directive.ts, projects/ngx-maplibre-gl/src/lib/image/image.component.ts, projects/ngx-maplibre-gl/src/lib/layer/layer.component.ts, projects/ngx-maplibre-gl/src/lib/map/map.component.ts, projects/ngx-maplibre-gl/src/lib/marker/marker.component.ts, projects/ngx-maplibre-gl/src/lib/markers-for-clusters/markers-for-clusters.component.ts, projects/ngx-maplibre-gl/src/lib/popup/popup.component.ts, projects/ngx-maplibre-gl/src/lib/source/canvas-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/geojson/feature.component.ts, projects/ngx-maplibre-gl/src/lib/source/geojson/geojson-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/raster-dem-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/raster-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/vector-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/video-source.component.ts, projects/showcase/src/app/app.config.ts, projects/showcase/src/app/doc/doc.component.ts, projects/showcase/src/styles.css, typedoc.json
Fixes #150 
This basically moves all the docs to the code itself in order to be able to generate a static site from it.
Currently it looks like the following:
I still need to understand how to properly integrate it into the current showcase.
My current solution is iframe, but I need to verify that it will work as expected.
=> Migrate to typedoc

projects/showcase/src/app/shared/layout/layout.component.ts
=> use same labels for mobile menu

README.md, projects/showcase/src/app/demo/stackblitz-edit/create-stackblitz-project.ts, projects/showcase/src/assets/stackblitz/main.notts
Seems like maplibre-gl and ngx-maplibre-gl do not rely on this fix anymore:
```
(window as any).global = window;
```
I removed it from the showcase app (https://github.com/maplibre/ngx-maplibre-gl/pull/157/commits/05b5424abb260646da6eed558871f91593f82770) and the map works as expected.
This removes it from the README "How to start" and from Stackblitz examples, simplifying the setup for new angular developers.
=> remove unused polyfill fix, remove from stackblitz too

.vscode/settings.json
While upgrading to SSR I had to inspect packages in node_modules. However, they are hidden in VSCode. I think it is useful to show the directory for inspecting installed packages.
=> show node_modules, useful to inspect installed packages

.github/workflows/ci.yml
Change `build-and-test` job to run on `ubuntu-latest` instead of `macos-latest`. 
Any particular reason `macos-latest` was used in this step?
Update also `actions/checkout` and `actions/upload-artifact` to latest version.
=> change build and test to run on ubuntu, update ci action version

projects/ngx-maplibre-gl/src/lib/markers-for-clusters/markers-for-clusters.component.ts
Seems like with Angular 18 the following error does not appear anymore https://github.com/maplibre/ngx-maplibre-gl/pull/168#issuecomment-2144789442
Works fine on following routes
http://localhost:4200/demo/cluster-html
http://localhost:4200/demo/ngx-cluster-html
=> Migrate markers cluster to new control flow

projects/ngx-maplibre-gl/src/lib/map/map.service.ts
`MapService.setup` is called in afterNextRender
* reference https://angular.dev/guide/experimental/zoneless#remove-ngzoneonmicrotaskempty-ngzoneonunstable-ngzoneisstable-or-ngzoneonstable
=> remove usage of NgZone.onStable and NgZone.onMicrotaskEmpty

projects/ngx-maplibre-gl/src/lib/markers-for-clusters/markers-for-clusters.component.ts
Fixes #184 by replacing feature.id with $index, as this causes warning in latest version of Angular.
- #184
=> A fix for the warnings related to track in latest version of angular

projects/ngx-maplibre-gl/src/lib/map/map.service.spec.ts, projects/ngx-maplibre-gl/src/lib/map/map.service.ts, projects/ngx-maplibre-gl/src/lib/popup/popup.component.ts
Fixes #193 by adding a subscription to all the events and unsubscribing when removing the relevant object.
I think this might cause some issue with the popup events, but I'm not sure which scenario is the right one and how it should behave.
In any case I think it's better than failing to present a popup.
- #193
=> Fix NG0953 caused by event errors

projects/ngx-maplibre-gl/src/lib/source/source.directive.spec.ts, projects/ngx-maplibre-gl/src/lib/source/source.directive.ts
Fixes #205
Current refresh mechanism of the source directive fails when updating the source id.
This is because it bases the removal call on the new id `this.id()` instead of the current one `this.sourceId()`.
=> fix: remove source based on current id during source update

projects/ngx-maplibre-gl/src/lib/control/control.component.ts, projects/ngx-maplibre-gl/src/lib/image/image.component.ts, projects/ngx-maplibre-gl/src/lib/layer/layer.component.ts, projects/ngx-maplibre-gl/src/lib/map/map.component.ts, projects/ngx-maplibre-gl/src/lib/marker/marker.component.ts, projects/ngx-maplibre-gl/src/lib/popup/popup.component.ts, projects/ngx-maplibre-gl/src/lib/source/geojson/feature.component.ts, projects/ngx-maplibre-gl/src/lib/source/image-source.component.ts, projects/ngx-maplibre-gl/src/lib/source/source.directive.ts, projects/showcase/src/app/demo/examples/live-update-feature.component.ts, projects/showcase/src/app/demo/examples/live-update-image-srource.component.ts, projects/showcase/src/app/demo/examples/marker-alignment.component.ts, projects/showcase/src/app/demo/examples/ngx-cluster-html.component.ts, projects/showcase/src/app/demo/stackblitz-edit/stackblitz-edit.component.ts, projects/showcase/src/app/shared/layout/layout-toolbar-menu.component.ts
This changes all the destroy methods to use ngOnDestory.
It fixes #207 apparently.
- #207
=> Align destroy calls

projects/ngx-maplibre-gl/src/lib/popup/popup.component.spec.ts, projects/ngx-maplibre-gl/src/lib/popup/popup.component.ts
Fixes #211 as this issue had two bug associated with it.
This is done by removing the popup using the map service (mainly unregistering the events) even in the case where marker was already destroyed.
=> Fix marker popup console error
